#ifndef TERMINALCHESS_CROSSPLATFORM_COMMANDLINE_H
#define TERMINALCHESS_CROSSPLATFORM_COMMANDLINE_H

void commandLineArguments(int& argc, char *argv[]);

#endif //TERMINALCHESS_CROSSPLATFORM_COMMANDLINE_H
