#ifndef TERMINALCHESS_CROSSPLATFORM_COMMANDLINE_H
#define TERMINALCHESS_CROSSPLATFORM_COMMANDLINE_H

void command_line_arguments(int& argc, char *argv[]);

#endif //TERMINALCHESS_CROSSPLATFORM_COMMANDLINE_H
